# Generated by Django 4.1 on 2022-08-13 18:54

import colorfield.fields
import common.file
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []